### ISSUE TITLE
Add nightly Job to drone

### ISSUE THREAD

**Issue by davitol** [owncloud/litmus-testing#2]
We want to run the tests nightly - so we need to add a nightly job

**Comment by tboerger** [comment]
They should be already running every night. /cc @patrickjahns

**Comment by davitol** [comment]
There was a typo in the config file

```
name: ownclou/litmus-testing
schedule: 0 30 1 * * *
```

A 'd' is missed in owncloud. @patrickjahns will take care of it.

**Comment by patrickjahns** [comment]
done
